
spring:
  cloud:
    consul:
      enabled: true
      host: 40.76.5.79
      port: 8500
      discovery:
        register: true
        discovery: enabled
        #prefer-ip-address: true
        #preferAgentAddress: true
        #healthCheckPath: /actuator/health
        healthCheckInterval: 60s
        port: 80
        hostname: ${WEBSITE_HOSTNAME}
        #instanceId: ${spring.application.name}:${random.value}
        healthCheckUrl: http://consul-spring-app.azurewebsites.net/actuator/health
        #tags: spring, profile=prod

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
      base-path: "/actuator"

endpoints:
  health:
    sensitive: false

logging:
  level:
    org.springframework.cloud.consul: DEBUG
    root: INFO
    #org.apache.http.wire: DEBUG
