apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: consul
    chart: consul-0.3.0
    component: server
    controller-revision-hash: consul-helm-server-f8bb7599f
    hasDNS: "true"
    release: consul-helm
    statefulset.kubernetes.io/pod-name: consul-helm-server-0
  name: consul-helm-server-lb
spec:
  ports:
  - name: port-1
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul
    component: server
    release: consul-helm
  type: LoadBalancer

